version: '3.8'

services:
  ecom-app:
    build: .
    image: ecom-app:latest
    container_name: ecom-app
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
      - SPRING_REDIS_DATABASE=0
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - ecom-network

  redis:
    image: redis:8.6-alpine
    container_name: ecom-redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data
    restart: unless-stopped
    networks:
      - ecom-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  redis-data:

networks:
  ecom-network:
    driver: bridge
