spring:
  application:
    name: ecom-app
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  data:
    redis:
      url: ${REDIS_URL}

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true
  info:
    env:
      enabled: true
info:
  app:
    name: EComApp
    description: Ecommerce app
    version: 1.0.1

jwt:
  secret: ${JWT_SECRET}